### ISSUE TITLE
Constants for evaluating .CPU need some rework

### ISSUE THREAD

**Issue by kugelfuhr** [cc65/cc65#2753]
There have some changes to `.cpu` and the constants to evaluate it lately. When looking at #2751 and #2749 I noticed that the constants have some problems.

The first one is that `.cpu` is internal to the assembler, but the constants to evaluate it are loaded via an include file. That's a bit strange, since `.cpu` cannot be used without these constants, and the include file is also tied closely to a specific assembler version. In my eyes, the constants should be assembler generated symbols instead. This would be cleaner and it would also allow to use these constants within assembler include files like zeropage.s resolving problems like in #2749. The symbols would have to be different from the current ones, since the existing ones are in the user name space. This could be achieved by using names using underscores or by moving them into a scope that has a name starting with an underscore. The existing include file should then map these names to the old ones and kept for some time for compatibility reasons.

The next thing is that `.cpu` describes existing CPU instruction sets. Unfortunately the instruction sets do not build nicely one upon the other. So it might be an idea to also include some information into the bits returned by `.cpu` that are not really a full instruction set. What I mean is for example that one bit might tell if the CPU supports `BRA` for an 8 bit distance. Currently this is supported by 65SC02, 65C02 and 65816 (I think) for which one is a superset of the other, so checking for 65SC02 is enough to find out if `BRA` is supported - for the three CPUs listed. But there's also the M740 which has `BRA` but is missing some other additional opcodes the 65SC02 has.

In most cases, `.cpu` is used to check for a specific instruction or addressing mode. So it might be an idea to either add a few bits to `.cpu` that tell if these instructions or addressing modes are available, or add another pseudo constant that contains this information. It might contain information about the following:

* `BRA` (short branch with 8 bit displacement)
* `PHX`/`PLX`/`PHY`/`PLY` (save and restore X/Y)
* `STA (zp)`/`LDA (zp)` (zero page indirect addressing for loads and stores) 
* `DEA`/`INA` (decrement and increment of the accumulator)
* Maybe others

**Comment by mrdudz** [comment]
Having those constants indicate individual instructions isnt terribly useful IMHO. In reality you'll end up writing specific code for specific CPUs anyway, and not ifdef every other instruction. I'd say this is a completely different problem from the first issue, and i wouldn't bother much about it. But if we really want such kind of mechanism, i'd vote for a seperate one from .cpu

**Comment by kugelfuhr** [comment]
Then, please look at the library. You'll find tons of stuff like:

```
.if (.cpu .bitand CPU_ISET_65SC02)
L3:     plx                     ; Low byte from stack into X
        rts                     ; A is already zero
.else
L3:     pla                     ; Low byte from stack ...
        tax                     ; ... into X
        lda     #$00            ; Clear low byte
        rts
.endif
```

or 

```
.if (.cpu .bitand CPU_ISET_65SC02)
        and     (c_sp)          ; 65SC02 version, saves 2 cycles and 1 byte
        ldy     #1
.else
        ldy     #0
        and     (c_sp),y
        iny
.endif
```

or 

```
.if (.cpu .bitand ::CPU_ISET_65SC02)
        lda     (c_sp)
.else
        ldy     #0              ; (2)
        lda     (c_sp),y        ; (7) Read byte
.endif
```

Actually most use cases in the library check for the availability of single instructions.

**Comment by mrdudz** [comment]
And now for the real issue
> The first one is that .cpu is internal to the assembler, but the constants to evaluate it are loaded via an include file. That's a bit strange, since .cpu cannot be used without these constants, and the include file is also tied closely to a specific assembler version. In my eyes, the constants should be assembler generated symbols instead. 

Yes, especially since everything is already there in cpu.c - it shouldn't be a big problem to get rid of cpu.mac alltogether

**Comment by kugelfuhr** [comment]
I wouldn't remove cpu.mac for some time. Otherwise you will break old code. But it would simply contain mappings from new assembler internal constants to the old names.

**Comment by mrdudz** [comment]
> Actually most use cases in the library check for the availability of single instructions.

I know those things of course - but the CPU stuff is totally sufficient for it. Once more than two super-closely related CPUs come into play, it will look different. As said, i doubt its terribly useful. 

> I wouldn't remove cpu.mac for some time. Otherwise you will break old code. But it would simply contain mappings from new assembler internal constants to the old names.

Why not just define the old names and be done with it? Afterall, one nice side effect of this change would be that you don't have to maintain two places that contain the exact some thing anymore

**Comment by kugelfuhr** [comment]
> I know those things of course - but the CPU stuff is totally sufficient for it. Once more than two super-closely related CPUs come into play, it will look different. As said, i doubt its terribly useful.

It requires the programmer to know the exact instructions sets of all CPUs. See my example for `bra` above. If you look into `atexit.s` you will see:

```
.if (.cpu .bitand ::CPU_ISET_65SC02)
        bra     doatexit
.else
        jmp     doatexit                ; Next one
.endif
```

Above code will not utilize `bra` when compiled for the m740. A programmer needs to know which chips support `bra` when using `.cpu` to check for it, and when new CPUs are added it might not work for these. Being able to check for specific instructions or addressing modes is definitely an advantage here.

> Why not just define the old names and be done with it? Afterall, one nice side effect of this change would be that you don't have to maintain two places that contain the exact some thing anymore

Because it breaks old code. But you might use the old names and supply an empty cpu.mac file (or one that emits a warning) instead.

**Comment by mrdudz** [comment]
> But you might use the old names and supply an empty cpu.mac file (or one that emits a warning) instead.

Of course, that'd be my solution. The point is, that if we change something in this area, it would be great to get rid of this cpu.mac vs the table in cpu.c - one of them must go :) I already had a very interesting moment the other day, because of slightly different data in those two :)

regarding testing for instructions, i have a more pragmatic approach to that than you do apparently. ie, what kind of code would likely ever appear in the common/shared part of the library anyway? I'd say it is 6502, R65C02, and 4510. Perhaps 6280.  And for those, the existing .cpu stuff works ok - most of the time anyway. (right now there is no 4510 nor 6280 in the shared code afaik)

As said, i'd just go for a separate mechanism, .cpufeatures (a bit long perhaps) or whatever. This doesn't have to be limited to just "instructions" either - it'd need some smart way for matching/testing though, as even 32bits will probably get full quickly

**Comment by kugelfuhr** [comment]
> As said, i'd just go for a separate mechanism, .cpufeatures (a bit long perhaps) or whatever. This doesn't have to be limited to just "instructions" either - it'd need some smart way for matching/testing though, as even 32bits will probably get full quickly

It could be a pseudo function that takes strings or identifiers. That would limit the test to one feature at a time but would on the other side allow an unlimited number of different arguments.

```
.if .cpufeat(HAS_BRA)
        bra     doatexit
.else
        jmp     doatexit                ; Next one
.endif
```
Maybe a name like `.capability` would be better. This would allow to use it for some other stuff, too.
```
.if .cap(CPU_HAS_BRA)
        bra     doatexit
.else
        jmp     doatexit                ; Next one
.endif
```

**Comment by mrdudz** [comment]
pseudofunc can have variable number of arguments, no? so .cap(HAS_BRA, HAS_FOO, etc) could work?

**Comment by kugelfuhr** [comment]
Yes that would work, good idea!

**Comment by kugelfuhr** [comment]
Wait. What does `.cap(HAS_BRA, HAS_FOO, etc)` mean? Is it a check for any of the arguments, or a check for all of them?

**Comment by mrdudz** [comment]
mmmmh i'd say "combined", ie all of them. my guess would be that you need that much more often than "any of these" (simply said, you put the instructions there that the following code uses - and you require them all, of course)

**Comment by kugelfuhr** [comment]
So how are the capabilities then?

* `CPU_ISET_65SC02` has `bra`, `ina`, `phx`, `stz` and `(zp)` addressing mode.
* `CPU_ISET_M740` has `bra`.

How about the others? The information in the "cpus.sgml" document seems to contradict the source code. The doc says:

* 65SC02 adds instructions to 6502.
* 65C02: The Rockwell extensions add additional bit manipulation and bit test-and-branch commands to the original 65SC02 instruction set (so its an extension to 65SC02).
* W65C02: Like 65C02 plus two instructions. So it is also capable of the 65SC02 instruction set.
* 65CE02: CSG took the Rockwell extensions and developed them further but it is missing two instructions from W65C02, so its an extension to the 65C02 and therefore capable of the 65SC02 instruction set.

So the instruction sets of the 65C02, W65C02 and 65CE02 are supersets to the 65SC02 according to the docs - but this is not mirrored in the source code. Or am I getting something wrong here? @mrdudz could you please explain?

**Comment by mrdudz** [comment]
> 65CE02: CSG took the Rockwell extensions and developed them further but it is missing two instructions from W65C02, so its an extension to the 65C02 and therefore capable of the 65SC02 instruction set.

Almost - Note also how the Z register was introduced.

"has z register" would be a good flag to have for this matter (this would be kinda equivalent with CE02 at this point)

> So the instruction sets of the 65C02, W65C02 and 65CE02 are supersets to the 65SC02 according to the docs - but this is not mirrored in the source code. Or am I getting something wrong here? @mrdudz could you please explain?

Is the confusion exactly about those opcodes using Z register? The Problem here is, that you cant just assemble eg ```sta (zp)``` as ```sta (zp),z``` on the 65CE02 - this compatibility only works on binary level IF you can make sure Z is 0 at all times. For this reason the CE02 (and above) Flags do not have the SC02 Flag ORd into them, neither does the assembler accept the instructions (without ,z), nor can we make sure z is 0 at all times (even if clearing it at startup, who knows what eg some rom call does).

IE i choose "source code compatible" to be the deciding factor for what goes in there.

Yes, that probably means a bunch of code currently guarded by SC02 will not be used for CE02 and up (*). But at least it will work instead of randomly crashing :) On the long run, this code should be tweaked to use either those new .cap flags, or actual CE02 code - i guess.

(*) going through the library and adding extra SE02 guard for those snippets that do not use the problematic instructions will be a job for a long boring evening...

**Comment by kugelfuhr** [comment]
So these CPUs are upwards compatible with the exception with the exception of the Z register? Which means that `stz` now means "store Z" instead of "store zero"? This would explain it of course. Thanks!

Regarding the `.cap` function: I will add `CPU_HAS_BRA8`, `CPU_HAS_INA`, `CPU_HAS_PUSHXY`, `CPU_HAS_STZ` and `CPU_HAS_ZPIND` (where `CPU_HAS_STZ` means "store zero") in a first implementation. These were the ones I found to be useful when checking the library sources. The list can be extended later, if required.

**Comment by mrdudz** [comment]
> Which means that stz now means "store Z" instead of "store zero"? This would explain it of course. Thanks!

exactly. The CE02 CPU guarantees Z to be 0 at powerup, so this way it can run older binaries.

**Comment by kugelfuhr** [comment]
There's still something strange. In cpu.c, the 65C02 sets the bits for `CPU_ISET_65C02` *and* `CPU_ISET_65SC02` which means that the instruction set of the 65C02 is a superset of the 65SC02. This is also in the docs.

However, the 4510 CPU has only `CPU_ISET_65C02` set, but not `CPU_ISET_65SC02`. But, if the 65C02 has all instructions of the 65SC02 CPU, wouldn't that mean that either `CPU_ISET_65SC02` has to be set for the 4510 CPU, or `CPU_ISET_65C02` has *not* to be set?

**Comment by mrdudz** [comment]
> However, the 4510 CPU has only CPU_ISET_65C02 set, but not CPU_ISET_65SC02. But, if the 65C02 has all instructions of the 65SC02 CPU, wouldn't that mean that either CPU_ISET_65SC02 has to be set for the 4510 CPU, or CPU_ISET_65C02 has not to be set?

Well the .cpu thing indicates which instruction sets you can use (again: source code compatibility). It isnt strictly related to how one cpu is based on the other. We could do that of course - but then the .cpu info becomes kind of pointless for anything in practise - we'd recreate the problem that was just fixed.

The individual bits for that matter then only indicate the instructions _added_ by that CPU, not the entire instruction set.

**Comment by kugelfuhr** [comment]
Sorry but I still do not understand. 

The current bits for `.cpu` as implemented in cpu.c tell me:
- If I have a 65C02 CPU I can use the full instruction set of the 65SC02.
- If I have a 4510 CPU I can use the full instruction set of the 65C02 CPU, but *not* that of the 65SC02 CPU.

These both statements contradict each other.

**Comment by mrdudz** [comment]
that "full" is not implied. you can use the instructions *added* by 65C02 (since 65SC02)

**Comment by kugelfuhr** [comment]
But that's not the way `.cpu` has been used. When doing

```
.if .cpu .bitand CPU_ISET_65C02
```

I'm not asking for some added instructions but if the full instruction set of the 65C02 can be used. Otherwise above test would indicate that I cannot use `PHX` and `PLY` - which is completely counter intuitive and extremely difficult to use. It requires that the programmer knows exactly which CPU added which instructions, which is a complete nightmare.

It seems you changed that in #2751 from the old behavior. I didn't realize this change otherwise I would have complained earlier.

**Comment by kugelfuhr** [comment]
If `.cpu` is kept this way the docs should be updated. Currently they say "It can also tell which instruction set the CPU is able to translate." which implies that a test

```
.if .cpu .bitand CPU_ISET_65C02
```

checks for the 65C02 instruction set - and not for a small part of it, as it is now.

**Comment by mrdudz** [comment]
It doesnt work the other way. Thats why #2751 was made in the first place. If each of these bits implies that every other "lower" bit is also set, then basically nothing that is CE02 or "higher" can use ANY of the "lower" bits, because they'd always imply SC02 is included - which doesnt work (the Z register problem). This idea worked when there was only chips up to the WDC65C02... add anything "higher" and it breaks.

And yes, i totally realize it changes the behaviour and may now "mask" (some, i doubt its much) CMOS code from being used when it was used before. I actually thought a lot of it, and its unfortunate indeed - but imho this is a necessary change and can not be avoided. AND nothing breaks in bad ways. And the impact on existing code should be close to non existent.

(And yes, the docs should be updated, obviously. You can safely assume that is the case for almost everything :))

**Comment by kugelfuhr** [comment]
Well I see the problem, but this change makes `.cpu` almost unusable for anything but very basic stuff. In this respect it is not better than before. What makes it worse is that it is counter intuitive now, since doing
```
.if .cpu .bitand CPU_ISET_65C02
```
does no longer mean I can use 65C02 instructions.

If (for example) I want to check for the availability of the `wai` instruction, I do now need intimate knowledge about which CPU added this instruction. It is no longer sufficient to know which CPU supports it as before, I need to know which CPU introduced it. Sorry - I don't know that, so I wouldn't be able to write such a check. And this is probably true for most other programmers.

As said above, I can see there's a problem, but I'm somewhat unhappy with the current solution.

**Comment by mrdudz** [comment]
As said, the previous scheme was busted, it couldn't handle more than those simple 3 or 4 cases correctly. And if we want to support any thing CE02 or higher, we can't use it anymore - at least not without completely degrading those CPUs, much more than now.

**Comment by mrdudz** [comment]
Oh and - this new capabilities thing, that could very well have fields with flags for certain entire instructions sets.... (And would you ever need anything else than "CMOS with Rockwell extensions" :))

**Comment by mrdudz** [comment]
guess we can close this :)
