### ISSUE TITLE
c64: using tgi with ser causes program to go off into weeds.

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#639]
I am writing a PLATO terminal for an online service (IRATA.ONLINE), and it needs bitmapped graphics output. However, if I use TGI calls while serial data is being processed, the program will go off into the weeds (PC becomes 0000), and I'm completely out of ideas on how to work around it. Can somebody take a look to see if there is indeed a problem? 

The following code has two branches, one for kernal serial routines, and one for a version of George Hug's 2400 baud userport routines that were wrapped in a ser driver.

http://github.com/tschak909/platoterm64

If somebody could at least look into it, that would be awesome. I am trying to produce something for the entire retro computing community, and this really puts the brakes on it. :(

-Thom

**Comment by oliverschmidt** [comment]
> [...] and one for a version of George Hug's 2400 baud userport routines that were wrapped in a ser driver.

https://github.com/cc65/wiki/wiki/Reminders#cbm-library says "Implement a Userport SER driver based on George Hug's 'Toward 2400' source code -- http://archive.org/details/transactor-magazines-v9-i03." so maybe there's a momentum to contribute such a driver...

**Comment by oliverschmidt** [comment]
> That's not the point [...]

Surely it isn't - what makes you think it was intended to be?

**Comment by tschak909** [comment]
Sorry, I thought the thread was being diverted. :)

-Thom

**Comment by polluks** [comment]
@tschak909 Oliver likes to recruit programmers :)

**Comment by tschak909** [comment]
That's all fine and dandy, but I'm dead in the water with this PLATO terminal, until I can figure out what in the hell is happening, and if I've stumbled on a conflict between tgi and ser, or not... :(

**Comment by oliverschmidt** [comment]
@polluks ;-))

@tschak909 Sorry for the misunderstadning I caused: My comment about the cc65 missing 2400 baud code was meant to attract cc65 community members to look at your problem because they see a potential synergy effect between solving it and getting that driver. So I _was_ actually trying to help you - indirectly.

**Comment by polluks** [comment]
I was using Frodo: crash
Well, there's no RS232 support at all.
Then I was using VICE: seems to work
BTW if you change to `tgi_install(tgi_static_stddrv)` you can remove your c64-hi.s.

**Comment by tschak909** [comment]
Oh, that's cool. ok. 

for me: 

I have VICE set to talk to tcpser on localhost:25232, with a speed of 2400 baud.

If I start using the modem (e.g. atdtirata.online:8005), it will freeze up after a few characters. 

This isn't happening, for you ?

**Comment by mrdudz** [comment]
you should really try this on a real c64 first - the RS232 emulation is barely working in VICE, it will show strange behaviour in many cases.

**Comment by tschak909** [comment]
Sigh,

Dude.

I do not have room on my bench for a C64. I am having to write _TWELVE_ implementations of this PLATO terminal. Emulation is my ONLY option. 

-Thom

**Comment by mrdudz** [comment]
that doesnt make what i said less valid - if you don't know if it even works on the real C64, its pointless to report a bug here.

**Comment by tschak909** [comment]
Actually, in point of fact, I asked a handful of people who DO have C64's to test on Facebook, last week. They report the same behavior.

Again, please, stop trying to throw red herrings. I am reasonably sure there is an odd bug here.

-Thom

**Comment by polluks** [comment]
Odd bug? This thread is about a bad tcpser https://www.forum64.de/index.php?thread/80683-c64-emulatoren-vice-und-daten%C3%BCbertragung-auf-telnet-bbs-systemen/&postID=1251535#post1251535

**Comment by tschak909** [comment]
The fozztexx fork of tcpser deals with this bug. Again. This is..not..the problem that's happening, here. :(

**Comment by tschak909** [comment]
I have to also point out, that the same behavior happens regardless of whether the kernal functions, or the up2400 driver and ser are used.

-Thom

**Comment by greg-king5** [comment]
As Stefan wrote, we no longer need to use the co65 utility.  Static copies of the drivers now are built into the libraries.  Therefore, you can remove the "c64-hi.s" and "c64-swlink.s" files.  Then, change the install function-calls to:
```C
ser_install(c64_swlink_ser);
tgi_install(tgi_static_stddrv);
```

The C64's TGI driver uses the RAM that's "behind" the I/O chips and the Kernal ROM.  It disables them while it's doing that.  The driver blocks maskable interrupts; but, it does nothing about Non-Maskable Interrupts.  RS-232 code uses NMIs.  NMIs aren't caught while the Kernal is "hidden" -- they execute garbage code!

Here's a little "trampoline" file that should fix the problem.  Call `install_nmi_tgi()` before the serial driver is openned.
[nmi-tgi.s.gz](https://github.com/cc65/cc65/files/1985159/nmi-tgi.s.gz)

**Comment by tschak909** [comment]
@greg-king5 Applied it to both branches (kernal and up2400). The symbol is there and it is being executed, but...

Kernal still shows the same behavior, while up2400 now JAMs when it crashes.

I'm guessing am doing something wrong:

Gist for Kernal version: https://gist.github.com/tschak909/656f9701c6d65c22fa93b40a12ff47ae

Gist for up2400 version: https://gist.github.com/tschak909/8cfece0809b46bc75f8dbaeaa298f0a0

**Comment by polluks** [comment]
@greg-king5 At least this should be part of the documentation.

**Comment by oliverschmidt** [comment]
@polluks: Why do you direct that comment to Greg? Is he responsible for the cc65 documentation?

**Comment by polluks** [comment]
@oliverschmidt It's his solution, the info should not get lost in this thread.

**Comment by greg-king5** [comment]
When I tried PlatoTerm,
```c
tgi_install(&c64_hi);
```
crashed.  But,
```c
tgi_install(tgi_static_stddrv);
```
worked.

I found a bug in "c64-hi.tgi".  Its implementation of `tgi_clear()` goes too far.  It zeroes _all_ of the top page of RAM.  That act "uninstalls" the NMI handler.  For a temporary work-around, swap the positions of the `tgi_clear()` and `install_nmi_tgi()` lines in "plato.c".

**Comment by tschak909** [comment]
Just tried ensuring that the nmi install happens after the clear, with slightly different results.. the kernel version now barfs out to BASIC. The up2400 version still freezes.

**Comment by tschak909** [comment]
as a test, if you're running tcpser appropriately configured e.g.

for the up2400 version
tcpser -v 25232 -s 2400 -i "&K0"

for the kernel version
tcpser -v 25232 -s 1200 -i "&K0"

typing ATDTIRATA.ONLINE:8005 should start the connection. 

-Thom

**Comment by mrdudz** [comment]
btw, a bit offtopic perhaps: wouldnt it a good idea if those drivers that require NMI or IRQ would set up the trampoline code so they keep working when high ROM is banked out? that would certainly give less surprising results in some cases :)

**Comment by oliverschmidt** [comment]
I fully agree that it is desirable that the scenario at hand works out of the box - especially as the current cc65 driver architecture is rather heavyweight anyway so the additional overhead might not be (too) significant.

However, I think that:
- Greg likely doesn‘t need anybody to get to that point of view.
- We might want to wait until the issue at hand is actually fixed to assess the options.

**Comment by tschak909** [comment]
I see the change to the lib in master, am going to try and test.

**Comment by tschak909** [comment]
Is the problem clearing up for you guys? I am still seeing the same problem, even after building the new library.

**Comment by polluks** [comment]
tgidemo & hitting restore a few times: crash
the routine nmi_tgi doesn't like `jsr vector`
my workaround: remove this line and nmi is happy

**Comment by polluks** [comment]
Indeed, these seem to be NMI critical:
* c64-c256k.emd
* c64-ram.emd
* c64-reu.emd
* c64-hi.tgi
* soft80 soft80mono

We need a few trampolines...

**Comment by tschak909** [comment]
I still have yet to get the swlink ser driver to even work (despite it working with CCGMS2017)...but that's another whole thread...one bug at a time. :)

**Comment by tschak909** [comment]
I'm sratching my head, even with the trampoline in place, it doesn't seem to make a dent, can anyone else reproduce this?

-Thom

**Comment by polluks** [comment]
Maybe an SEI is missing?

**Comment by tschak909** [comment]
nope, plopped it in between every possible line before the main loop, behaviors ranged from no processed serial input, to the typical behavior I see (hard crash while receiving data.)

**Comment by mrdudz** [comment]
i dont have time to debug this in detail, but i would do is...

- run your program in vice
- enter the monitor
- set a watchpoint on the nmi vector (watch fffa fffb)
- exit the monitor (x)
- now send one byte to the emulator via "rs232"
- the watchpoint should trigger
- set monitor to cpu bank (bank cpu) so you always see what the cpu is seeing
- now singlestep (z) until it goes berzerk
- stare at the output and find out what went wrong :)

**Comment by tschak909** [comment]
Greg King provided a patch to the nmi trampoline, which I applied, and tested.

(1) the master branch still crashes after a few bytes (it starts to draw, then freezes, with little bits of graphic corruption happening.
(2) the up2400 branch doesn't send any serial data or display any output after the port is opened and run. 

[code]
void main(void)
{
  int i=0;

  struct ser_params params = {
    SER_BAUD_2400,
    SER_BITS_8,
    SER_STOP_1,
    SER_PAR_NONE,
    SER_HS_NONE
  };

  c=ser_install(&c64_up2400);

  if (c!=SER_ERR_OK)
    {
      printf("ser_install returned: %d\n",c);
      return;
    }

  y=511-16;
  deltax=8;
  deltay=16;
  dumb_terminal_active=1;
  tgi_install(tgi_static_stddrv);
  tgi_init();

  install_nmi_trampoline();

  tgi_clear();

  c=ser_open(&params);
  ser_ioctl(1, NULL);

  greeting();

  for(;;)

  greeting();

  // And do the terminal
  for (;;)
    {
      if (ser_get(&c)==SER_ERR_OK)
        {
          decode(c);
        }
      if (kbhit())
        {
          ser_put(cgetc());
        }
    }

  tgi_done();
  ser_close();
  ser_uninstall();
  tgi_uninstall();
}
[/code]

**Comment by greg-king5** [comment]
There's an infinite loop in the up2400 branch:
```c
  ser_ioctl(1, NULL);

  greeting();

  for(;;)

  greeting();

  // And do the terminal
  for (;;)
```
You must remove the first `greeting();` and the first `for (;;)`.

---
I don't see any graphics.  I see the irata.online server's greeting.  Then, I see characters that I assume are Plato commands.

**Comment by tschak909** [comment]
Oop, damn it, that was a merge conflict that I didn't quite resolve quite correctly 👍 

I am a bit confused though, even with the nmi trampoline corrected and in place, I am still getting crashes when serial data comes in, it's intermittent, sometimes it happens immediately, sometimes it's after a few lines have come in. Are you testing on real hardware? I don't have any, am using winvice 3.1... (I am trying to get a friend's 128 so I can do some real hardware testing).

**Comment by greg-king5** [comment]
I, too, am using VICE on Windows.

**Comment by tschak909** [comment]
and it's _not_ crashing for you?

**Comment by groessler** [comment]
@tschak909: Could you give some setup instructions for dummies? I could try VICE and real C64 (C128 in C64 mode) with a Swiftlink adapter. You gave me already access to IRATA.ONLINE, which to my embarrassment, I haven't tried yet. Sorry.

**Comment by tschak909** [comment]
The Swiftlink adaptor has already been tried, it doesn't seem to work, I keep getting an error 8, and the other testers experienced the same problem.

This software is nowhere near the point where users can actually use it, you'd need to change the serial driver that's built into the binary, etc.

I really need to figure out wtf I am doing wrong with this nmi trampoline, so I can get to debugging the protocol.

**Comment by groessler** [comment]
Just wanted to try it out myself (and maybe help). So, just with VICE, what are the steps to connect? (Ideally, ignoring that it doesn't seem to work currently.)

**Comment by tschak909** [comment]
First, compile PLATOTerm. The makefile is there to be able to produce a PRG file that can be plopped onto a disk.

Before PLATOTerm starts, you must set User Port serial port emulation up, with e.g. 2400 bps baud rate.

You then point that to a running tcpser installation set up e.g.

tcpser -v 25232 -s 2400 -i "&K0"

and then you should be able to launch PLATOTerm.

Once PLATOTerm starts,

You can now type:

ATDTirata.online:8005 to connect.

But, there are still problems, namely

* NMI bug causes output to freeze when serial input happens. (show stopper)
* 8th bit must be stripped from incoming data (have a push ready for this)
* telnet escape sequences for 0xFF are sent (IAC escapes), this needs to be stripped (TODO)
* modify up2400 to handle 7-bit data and parity bit generation. Yes, this is required. (TODO)

-Thom

**Comment by groessler** [comment]
Ok. Will try. One last thing: Where can I find a "known good" tcpser version?

**Comment by tschak909** [comment]
https://github.com/FozzTexx/tcpser

**Comment by groessler** [comment]
Thanks!

**Comment by groessler** [comment]
Still a problem (haven't used VICE much).

> You then point that to a running tcpser installation set up e.g.

How?

**Comment by tschak909** [comment]
Go into RS232 settings. You will find 4 IP address entries to point to a tcpser installation. probably 127.0.0.1 port 25232, set the user port emulation to one of those ports, and run tcpser as above.

-Thom

**Comment by groessler** [comment]
I didn't continue yesterday, because I got distracted, and more important, I didn't find a menu entry with "IP address" in my VICE. I'm using VICE 3.1 which comes with Fedora 27.

**Comment by tschak909** [comment]
Believe it or not, that's okay. The protocol decoder needs some tweaking. I've done some changes if you want to pull them over.

I am connected to tcpser in exactly the same way, but this is what happens , for me:

<img width="433" alt="platoterm64_hung" src="https://user-images.githubusercontent.com/2759782/40429524-84fe96f8-5e68-11e8-8401-460b369dfa2f.PNG">

(I have experimented with placing the trampoline at various spots in the code)

plato.c is currently
--------------------
<pre>
void main(void)
{
  int i=0;

  struct ser_params params = {
    SER_BAUD_2400,
    SER_BITS_8,
    SER_STOP_1,
    SER_PAR_NONE,
    SER_HS_NONE
  };

  
  c=ser_install(&c64_up2400);

  if (c!=SER_ERR_OK)
    {
      printf("ser_install returned: %d\n",c);
      return;
    }

  y=511-16;
  deltax=8;
  deltay=16;
  dumb_terminal_active=1;
  install_nmi_trampoline();
  tgi_install(tgi_static_stddrv);
  tgi_init();



  tgi_clear();
  
  c=ser_open(&params);
  ser_ioctl(1, NULL);  
    
  greeting();

  // And do the terminal
  for (;;)
    {
      if (ser_get(&c)==SER_ERR_OK)
	{
	  // Detect and strip IAC escapes (two consecutive bytes of 0xFF)
	  if (c==0xFF && lastc == 0xFF)
	    {
	      lastc=0x00;
	    }
	  else
	    {
	      decode(c&0x7F);
	      lastc=c;
	    }
	}
      if (kbhit())
	{
	  ser_put(cgetc());
	}
    }

  tgi_done();
  ser_close();
  ser_uninstall();
  tgi_uninstall();
}
</pre>

Am really confused. :(

**Comment by tschak909** [comment]
@groessler first, look for RS232 settings. Set your tcpser endpoint there.

Then, 
For ACIA based emulation, look at ACIA Settings.
For User port based emulation, look at RS232 Userport Settings.

-Thom

**Comment by groessler** [comment]
> look for RS232 settings. Set your tcpser endpoint there.

Where?

![vice-rs232](https://user-images.githubusercontent.com/4138182/40430807-4042dc84-5ea6-11e8-85ab-480856588482.png)

**Comment by tschak909** [comment]
Have you gone into Serial 1 device and baud rate?

-Thom

**Comment by groessler** [comment]
I was in Serial1->device, but it seems to just let me pick a physical device of the host computer.

**Comment by greg-king5** [comment]
> I was in Serial1->device; but, it seems to just let me pick a physical device of the host computer.

You can try devices 3 and 4.  You can hope that they aren't limited to doing what the submenu claims about them.

**Comment by tschak909** [comment]
Also, that doesn't look like VICE 3.1... You may want to build vice from source, and e.g. use the SDL backend.

-Thom

**Comment by groessler** [comment]
@tschak909: it reports itself as 3.1, see
![vice-version](https://user-images.githubusercontent.com/4138182/40433857-585c17ac-5ead-11e8-952e-57a086d94542.png)
But I will build from source, maybe some configuration options weren't given in the "distribution build".

@greg-king5: How to try devices 3 and 4? There are no menu entries for them.

**Comment by polluks** [comment]
Who needs a UI? Simply edit vice.ini yourself ;-)

**Comment by Compyx** [comment]
I would normally suggest building VICE from trunk, but since we're in the process of removing a lot of (now) unused code, better try the recent 3.2 tarball.
As for the confusing UI stuff, going on from 3.2, there's only a Gtk3 UI (for any system that supports it) and an SDL UI (for those who don't, or as a fall back).

**Comment by greg-king5** [comment]
I built tcpser and PLATOTerm from unmodified clones of their repositories.  I built them in both Cygwin and MSYS2.
I used SDL1 VICE, GTK3 VICE, and WinVICE.
I tested them on 32-bit Windows 7 and 64-bit Windows 10.

**Comment by greg-king5** [comment]
@groessler, the "last" submenu in your picture shows four lines:

1. "Serial 1"
2. "Serial 2"
3. "Dump to file"
4. "Exec process"

Those should be four RS-232 "devices", in spite of what the submenu implies.

**Comment by tschak909** [comment]
Once again, completely side-stepping my explicit question... *facepalm* 

No matter which branch I try, or where I place the #@()$@#( trampoline, the program crashes during serial input.

(I am building with the latest cc65 from git btw, quite literally)

I am _this_ close to completely jettisoning the serial port stuff and trying to hack in IP65. I didn't want to do this yet, because a lot more people have serial modems, and this will severely limit who can use the software, but..hey..nobody else gives a $(#)@ about this, but me, right? :)

<-- FRUSTRATED

-Thom

**Comment by polluks** [comment]
@tschak909 What happens if you don't use TGI at all? We have to be absolutely sure it's still an NMI problem.

**Comment by tschak909** [comment]
Then the program runs normally. I did the initial serial test using the main loop of the program rendering out to the direct crt i/o. The problems only started happening once I folded in TGI.

**Comment by polluks** [comment]
@tschak909 How about this: You change c64-hi to use another memory area which doesn't require extra NMI? The C128 uses $2000-$3FFF...

**Comment by tschak909** [comment]
k, great, got a patch? 

-Thom

**Comment by polluks** [comment]
At least less work than fiddling IP65 ;-)

**Comment by oliverschmidt** [comment]
> At least less work than fiddling IP65 ;-)

If you think so ;-))

**Comment by tschak909** [comment]
and honestly, ok, great, if you're using the code as it is from the repo, which branch? There are two. (a kernel routine one and ser based one, both are crashing for me)... is it something in my vice config? (some obscure virtual device trap maybe?), bc if you're getting to the banner....

:-(

**Comment by groessler** [comment]
yesterday I built VICE 3.2 from tarball. With `--enable-native-gtk3ui --disable-nls --enable-ethernet --enable-cpuhistory --enable-debug` configure options. The pull-down menus now look differently, but still no "IP address" or Network settings in the rs232 settings.

I have an idea what to try next: Use "4) exec process". I'm assuming this process' stdout will be serial input data, and serial output sent to stdin.

Does anyone know of a simple serial test program for C64. Maybe just some BASIC program.

**Comment by polluks** [comment]
@groessler BASIC? testcode/lib/ser-test.c

**Comment by tschak909** [comment]
@groessler try adding this to your vice config file in the [C64] section:
RsDevice1="192.168.1.3:25232"

replace the IP address appropriately.

I just tried the Linux version of VICE, and ... I'm honestly extremely disappointed at the changes that have been made. 

-Thom

**Comment by tschak909** [comment]
Ok, so master is the kernel version, that is set at 1200bps, 

When I run it, the system crashes, ranging from JAM to a restore style break back to BASIC, when serial output starts to come in.

can you attach a binary? 

-Thom

**Comment by groessler** [comment]
[plato.zip](https://github.com/cc65/cc65/files/2036949/plato.zip)

**Comment by groessler** [comment]
And, yes, the first char when I try to type the "ADTDxxx" string gets lost. Is that happening for you, too?

**Comment by tschak909** [comment]
yes, that happens. ok, wth, this one works fine... This is WEIRD.

**Comment by groessler** [comment]
I'm getting the same plato binary when compiling with newest cc65.

Are you sure that your cc65 is in good shape? Try `git diff` to see potential local changes. Get newest version (`git pull`). Then `make clean; make` to build a fresh version.

**Comment by tschak909** [comment]
I'm blasting my whole cc65 installation.

**Comment by tschak909** [comment]
it must have been my compiler. :( hmm...

**Comment by groessler** [comment]
does it work for you now?

**Comment by tschak909** [comment]
Yup, seems to. now off to debug the protocol handler.

**Comment by spiro-trikaliotis** [comment]
@groessler 
> Baud to 1200 (although I don't understand why the baud setting matters, it's just pipes and TCP traffic. But it didn't work if set to a different value.)"

For the KERNAL routine, VICE performs the bit-banging that the KERNAL routines assume to get on the user port for receiving, and it performs the bit-banging to get the data from the KERNAL in the time frame that is needed.

Of course, VICE could also do some auto-detecting by looking at the length of the start bit, bit this has not been implemented.

**Comment by groessler** [comment]
> For the KERNAL routine, VICE performs the bit-banging that the KERNAL routines assume to get on the user port for receiving, and it performs the bit-banging to get the data from the KERNAL in the time frame that is needed.

Ok. I don't understand the details here, but it seems there is an explainable reason for the dependency on the baud rate. :-)

> Of course, VICE could also do some auto-detecting by looking at the length of the start bit, bit this has not been implemented.

Probably that's obvious when one understands the part above, but what is the "lenght of the start bit" in TCP connections? ("lenght" refers to the "length in time", I guess)?

**Comment by tschak909** [comment]
you're thinking of it from the wrong end.

The baud rate matters because VICE is literally having to simulate serial data flowing into the I/O pins on the user port.

This needs a baud (clock) rate to determine among other things, the timing for the start, stop, and data bits.

**Comment by groessler** [comment]
Ok. I think I'm getting a rough idea how this work son C64 now. Thanks.

**Comment by spiro-trikaliotis** [comment]
@groessler , look at it like this:
When you send a character to the C64 via serial, then VICE internally creates the wave form that is needed on the user port in order for the KERNAL routine to recognize this bit.

Assume, the character starts it some point of time "t".

Then, VICE will start the start bit on time "t", the first bit of your character (bit 0) at time "t+dt", the second bit of your character (bit 1) at time "t+2dt", and so on.

In order to choose the right dt, it has to know the bit rate.

The same in the opposite direction: When the C64 sends out serial data, it creates such a waveform. As VICE has to recognize this waveform, it has to know which dt to use so it knows when which bit is currently "on the (virtual) user port line".

The auto-detection would work as follows: As soon as the C64 sends something, it issues a start bit. The start bit starts at the first change on the line, and it ends at the second change of the line. With this, VICE could determine the dt, and use it for this character, as well as for sending data to the emulated C64. With every byte from the C64, VICE would have to check if the start bit still has the length, as the baud rate could have changed.

This approach would fail on asymmetric baud rates (like 1200/75), though. But IIRC, the C64 does not support that, anyway.

As no communication will be done to the C64 until the C64 had send out at least one byte (why should tcpser contact the emulated C64?), this could be done.

Note that even for the more sophisticated RS232 implementations, VICE uses the baud rate. It uses it so it does not "overload" the C64 by sending the characters faster than the program expects them, or slower than necessary.

**Comment by groessler** [comment]
Understood, @spiro-trikaliotis. Thanks!

**Comment by groessler** [comment]
It appears the problem was solved. Closing issue....
